title:              Being Frank.
email:              franktcao@gmail.com
description:        Life, Tech, and Happiness
author:             Frank Cao
baseurl:            ""
url:                "https://franktcao.github.io"


#highlighter:        rouge

# Social Profiles
#twitter_username:   SBootstrap
github_username:    franktcao
#facebook_username:  franktcao
linkedin_username:  franktcao

# Add your google-analytics ID here to activate google analytics
google_analytics:   #UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-clean-blog
